"""create 3 tables: users user_goals body_measurements

Revision ID: ec5983897455
Revises: 
Create Date: 2026-07-20 21:39:52.899699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5983897455'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('bicep', sa.Float(), nullable=True),
    sa.Column('thigh', sa.Float(), nullable=True),
    sa.Column('calf', sa.Float(), nullable=True),
    sa.Column('squat_1rm', sa.Float(), nullable=True),
    sa.Column('bench_1rm', sa.Float(), nullable=True),
    sa.Column('deadlift_1rm', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_body_measurements_user_recorded', 'body_measurements', ['user_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_body_measurements_recorded_at'), 'body_measurements', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('cut', 'bulk', 'maintain', 'strength', name='goal_type'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='goal_status'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_goals_user_status', 'user_goals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_goals_status'), 'user_goals', ['status'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_status'), table_name='user_goals')
    op.drop_index('idx_user_goals_user_status', table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_recorded_at'), table_name='body_measurements')
    op.drop_index('idx_body_measurements_user_recorded', table_name='body_measurements')
    op.drop_table('body_measurements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
